---
- name: Add repository-gpg-key for fastd
  apt_key: 
    keyserver: "{{ pgp_keyserver }}"
    id: "{{ fastd_repository_key }}"

- name: add universe-factory and wheezy-backports repositories for fastd
  apt_repository:
    repo: "deb http://repo.universe-factory.net/debian/ sid main"
    update_cache: yes

- name: add wheezy-backports
  apt_repository:
    repo: "deb http://ftp.debian.org/debian/ wheezy-backports main"
    update_cache: yes
  when: ansible_distribution=="Debian" and ansible_distribution_release=="wheezy"

- name: install fastd
  apt:
    name: fastd
    state: present
    force: yes

- name: fastd directories
  file: 
    path: "/etc/fastd/{{ fastd_interface }}"
    state: directory

- name: fastd.conf
  template:
    src: "fastd.conf.j2"
    dest: "/etc/fastd/{{ fastd_interface }}/fastd.conf"
    owner: root
    group: root
    mode: '0600'
  notify: 
  - restart fastd

- name: peers_dirs
  file:
    path: "/etc/fastd/{{ fastd_interface }}/{{ item.value.peers_dir }}"
    state: directory
  with_dict: fastd_peers
  notify:
  - restart fastd

- name: Verifying configuration
  shell: fastd --verify-config -c /etc/fastd/{{ fastd_interface }}/fastd.conf

